name: NGINX build
on:
  schedule:
  - cron: '0 0 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    name: NGINX build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: ./
      - name: Hash
        run: |
          hash=$(md5sum /home/runner/work/_temp/_github_home/nginx.deb | awk '{print $1}')
          echo "hash=${hash:0:7}" >> $GITHUB_ENV
      - name: Upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: nginx-${{ env.hash }}.deb
          path: /home/runner/work/_temp/_github_home/nginx.deb
